version: 2.1
orbs:
  node: circleci/node@1.1.6
  gcp-gke: circleci/gcp-gke@1.0.3
  gcr: circleci/gcp-gcr@0.6.1
jobs:
  build:
    description: Install npm
    # machine option runs your jobs in a dedicated, ephemeral VM that has the following specifications:
    machine: true
    steps:
      - checkout
      # Install node
      - node/install
      # Install npm
      - node/install-npm
      # Download and cache dependencies
      - node/with-cache:
          steps:
            - run:
                name: Install application dependencies
                command: npm install
          # Save cache
          cache-key: package.json
          # Ignore non-checksum cache hits
          use-strict-cache: true
  Build-Push-Image-Docker:
    description: Build and push image to Google Container Registry
    machine: true
    steps:
      - checkout
      - gcr/gcr-auth
      - gcr/build-image:
          image: circleci-gke
          tag: "v123" #Change version number e.g to 'v3' when updating application
      - gcr/push-image:
          image: circleci-gke
          tag: "v123" #Change version number e.g to 'v3' when updating application
    
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    steps:
      # Install `gcloud` and `kubectl` if not already installed.
      - gcp-gke/install

      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: coding-experiment-cluster-1
          install-kubectl: true
          perform-login: true

      - gcp-gke/rollout-image:
          deployment: production-circle-demo
          cluster: coding-experiment-cluster-1
          container: circleci-gke
          image: gcr.io/api-project-264252978677/circleci-gke:v123 # change version when updating
workflows:
  build_update_deploy:
    jobs:
      - build
      - Build-Push-Image-Docker:
          requires:
            - build
      - deploy:
          requires:
            - Build-Push-Image-Docker